CREATE TABLE `instagram_comments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `comment_id` bigint DEFAULT NULL,
  `post_id` int DEFAULT NULL,
  `text` text,
  `created_at` bigint DEFAULT NULL,
  `owner_id` bigint DEFAULT NULL,
  `owner_username` varchar(255) DEFAULT NULL,
  `owner_is_verified` tinyint(1) DEFAULT NULL,
  `owner_profile_pic_url` varchar(1024) DEFAULT NULL,
  `likes` int DEFAULT NULL,
  `replies` int DEFAULT NULL,
  `sentiment` varchar(20) DEFAULT NULL,
  `player_mentioned` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `comment_id` (`comment_id`),
  KEY `idx_post_id` (`post_id`),
  CONSTRAINT `fk_post_id` FOREIGN KEY (`post_id`) REFERENCES `instagram_posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=48265 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `instagram_posts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `shortcode` varchar(32) DEFAULT NULL,
  `post_type` varchar(50) DEFAULT NULL,
  `is_reel` tinyint(1) DEFAULT NULL,
  `taken_at` datetime(6) DEFAULT NULL,
  `taken_at_timestamp` bigint DEFAULT NULL,
  `caption` text,
  `like_count` int DEFAULT NULL,
  `comment_count` int DEFAULT NULL,
  `video_view_count` int DEFAULT NULL,
  `media_count` int DEFAULT NULL,
  `location_name` varchar(255) DEFAULT NULL,
  `location_address` varchar(255) DEFAULT NULL,
  `location_city` varchar(255) DEFAULT NULL,
  `location_latitude` double DEFAULT NULL,
  `location_longitude` double DEFAULT NULL,
  `owner_username` varchar(255) DEFAULT NULL,
  `owner_full_name` varchar(255) DEFAULT NULL,
  `owner_is_verified` tinyint(1) DEFAULT NULL,
  `owner_is_private` tinyint(1) DEFAULT NULL,
  `accessibility_caption` text,
  `is_paid_partnership` tinyint(1) DEFAULT NULL,
  `tagged_users` json DEFAULT NULL,
  `from_api` tinyint(1) DEFAULT NULL,
  `url` varchar(512) DEFAULT NULL,
  `image_width` int DEFAULT NULL,
  `image_height` int DEFAULT NULL,
  `estimated_reach` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `shortcode` (`shortcode`)
) ENGINE=InnoDB AUTO_INCREMENT=825 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `logo_detections` (
  `id` int NOT NULL AUTO_INCREMENT,
  `post_id` int NOT NULL,
  `logo_label` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `confidence` decimal(5,4) NOT NULL,
  `box_x` decimal(10,2) NOT NULL,
  `box_y` decimal(10,2) NOT NULL,
  `box_width` decimal(10,2) NOT NULL,
  `box_height` decimal(10,2) NOT NULL,
  `model_version` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'best.onnx',
  `confidence_threshold` decimal(3,2) NOT NULL,
  `detected_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `verified` tinyint(1) DEFAULT '0',
  `verified_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `verified_at` timestamp NULL DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `visibility_score` decimal(10,4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_post_id` (`post_id`),
  KEY `idx_logo_label` (`logo_label`),
  KEY `idx_confidence` (`confidence`),
  KEY `idx_detected_at` (`detected_at`),
  KEY `idx_verified` (`verified`),
  CONSTRAINT `fk_logo_detections_post_id` FOREIGN KEY (`post_id`) REFERENCES `instagram_posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=25395 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `matches` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fotmob_match_id` int NOT NULL,
  `page_url` varchar(500) DEFAULT NULL,
  `home_team_id` int NOT NULL,
  `home_team_name` varchar(255) NOT NULL,
  `home_team_score` int DEFAULT NULL,
  `away_team_id` int NOT NULL,
  `away_team_name` varchar(255) NOT NULL,
  `away_team_score` int DEFAULT NULL,
  `opponent_id` int DEFAULT NULL,
  `opponent_name` varchar(255) DEFAULT NULL,
  `opponent_score` int DEFAULT NULL,
  `tournament_name` varchar(255) DEFAULT NULL,
  `tournament_league_id` int DEFAULT NULL,
  `display_tournament` tinyint(1) DEFAULT '1',
  `match_result` tinyint DEFAULT NULL,
  `not_started` tinyint(1) DEFAULT '1',
  `match_utc_time` datetime DEFAULT NULL,
  `finished` tinyint(1) DEFAULT '0',
  `started` tinyint(1) DEFAULT '0',
  `cancelled` tinyint(1) DEFAULT '0',
  `awarded` tinyint(1) DEFAULT '0',
  `score_str` varchar(50) DEFAULT NULL,
  `status_reason_short` varchar(50) DEFAULT NULL,
  `status_reason_short_key` varchar(100) DEFAULT NULL,
  `status_reason_long` varchar(255) DEFAULT NULL,
  `status_reason_long_key` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `fotmob_match_id` (`fotmob_match_id`),
  KEY `idx_home_team` (`home_team_id`),
  KEY `idx_away_team` (`away_team_id`),
  KEY `idx_tournament` (`tournament_league_id`),
  KEY `idx_match_utc_time` (`match_utc_time`),
  KEY `idx_finished` (`finished`),
  KEY `idx_not_started` (`not_started`)
) ENGINE=InnoDB AUTO_INCREMENT=322 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `player_match_performance` (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NOT NULL,
  `match_id` int NOT NULL,
  `match_date` datetime DEFAULT NULL,
  `league_name` varchar(255) DEFAULT NULL,
  `is_home_team` tinyint(1) DEFAULT NULL,
  `player_name` varchar(255) DEFAULT NULL,
  `opta_id` varchar(50) DEFAULT NULL,
  `team_id` int DEFAULT NULL,
  `team_name` varchar(100) DEFAULT NULL,
  `is_goalkeeper` tinyint(1) DEFAULT '0',
  `fotmob_rating` decimal(4,2) DEFAULT NULL,
  `minutes_played` int DEFAULT '0',
  `goals` int DEFAULT '0',
  `assists` int DEFAULT '0',
  `yellow_cards` int DEFAULT '0',
  `red_cards` int DEFAULT '0',
  `xg` decimal(5,2) DEFAULT NULL,
  `xg_on_target` decimal(5,2) DEFAULT NULL,
  `xa` decimal(5,2) DEFAULT NULL,
  `xg_xa` decimal(5,2) DEFAULT NULL,
  `total_shots` int DEFAULT '0',
  `shots_on_target` int DEFAULT '0',
  `accurate_passes` int DEFAULT '0',
  `total_passes` int DEFAULT '0',
  `pass_accuracy_percentage` decimal(5,2) DEFAULT NULL,
  `chances_created` int DEFAULT '0',
  `accurate_long_balls` int DEFAULT '0',
  `total_long_balls` int DEFAULT '0',
  `touches` int DEFAULT '0',
  `touches_in_opp_box` int DEFAULT '0',
  `successful_dribbles` int DEFAULT '0',
  `total_dribbles` int DEFAULT '0',
  `dribble_success_percentage` decimal(5,2) DEFAULT NULL,
  `dispossessed` int DEFAULT '0',
  `errors_led_to_goal` int DEFAULT '0',
  `big_chances_missed` int DEFAULT '0',
  `dribbled_past` int DEFAULT '0',
  `tackles` int DEFAULT '0',
  `interceptions` int DEFAULT '0',
  `clearances` int DEFAULT '0',
  `blocks` int DEFAULT '0',
  `recoveries` int DEFAULT '0',
  `defensive_actions` int DEFAULT '0',
  `headed_clearances` int DEFAULT '0',
  `duels_won` int DEFAULT '0',
  `duels_lost` int DEFAULT '0',
  `ground_duels_won` int DEFAULT '0',
  `total_ground_duels` int DEFAULT '0',
  `aerial_duels_won` int DEFAULT '0',
  `total_aerial_duels` int DEFAULT '0',
  `fouls_committed` int DEFAULT '0',
  `was_fouled` int DEFAULT '0',
  `saves` int DEFAULT '0',
  `goals_conceded` int DEFAULT '0',
  `xgot_faced` decimal(5,2) DEFAULT NULL,
  `goals_prevented` decimal(5,2) DEFAULT NULL,
  `diving_saves` int DEFAULT '0',
  `saves_inside_box` int DEFAULT '0',
  `high_claims` int DEFAULT '0',
  `punches` int DEFAULT '0',
  `throws` int DEFAULT '0',
  `acted_as_sweeper` int DEFAULT '0',
  `fun_facts` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_player_match` (`player_id`,`match_id`),
  KEY `idx_player_id` (`player_id`),
  KEY `idx_match_id` (`match_id`),
  KEY `idx_rating` (`fotmob_rating`),
  KEY `idx_goals` (`goals`),
  KEY `idx_assists` (`assists`),
  KEY `idx_minutes` (`minutes_played`),
  KEY `idx_match_date` (`match_date`),
  CONSTRAINT `fk_match` FOREIGN KEY (`match_id`) REFERENCES `matches` (`fotmob_match_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_player` FOREIGN KEY (`player_id`) REFERENCES `players` (`fotmob_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2382 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `players` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fotmob_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `shirt_number` int DEFAULT NULL,
  `country_code` char(3) DEFAULT NULL,
  `country_name` varchar(100) DEFAULT NULL,
  `role_key` varchar(50) DEFAULT NULL,
  `role_fallback` varchar(50) DEFAULT NULL,
  `position_id` int DEFAULT NULL,
  `position_ids` varchar(100) DEFAULT NULL,
  `position_ids_desc` varchar(100) DEFAULT NULL,
  `position_group` varchar(50) DEFAULT NULL,
  `height` int DEFAULT NULL,
  `age` int DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `injured` tinyint(1) DEFAULT '0',
  `injury_id` varchar(50) DEFAULT NULL,
  `injury_expected_return` varchar(100) DEFAULT NULL,
  `rating` decimal(4,2) DEFAULT NULL,
  `goals` int DEFAULT '0',
  `penalties` int DEFAULT '0',
  `assists` int DEFAULT '0',
  `red_cards` int DEFAULT '0',
  `yellow_cards` int DEFAULT '0',
  `exclude_from_ranking` tinyint(1) DEFAULT '0',
  `transfer_value` bigint DEFAULT NULL,
  `instagram_url` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `aliases` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `fotmob_id` (`fotmob_id`),
  KEY `idx_name` (`name`),
  KEY `idx_position_group` (`position_group`),
  KEY `idx_country` (`country_code`),
  KEY `idx_rating` (`rating`),
  KEY `idx_injured` (`injured`)
) ENGINE=InnoDB AUTO_INCREMENT=192 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE ALGORITHM=UNDEFINED DEFINER=`remote`@`%` SQL SECURITY DEFINER VIEW `instagram_post_sentiment` AS select `ic`.`post_id` AS `post_id`,coalesce(avg((case when (lower(`ic`.`sentiment`) = 'positive') then 1 when (lower(`ic`.`sentiment`) = 'negative') then -(1) else 0 end)),0) AS `sentiment_score`,count(0) AS `comment_count` from `instagram_comments` `ic` group by `ic`.`post_id`;

